### ISSUE TITLE
Bug in regex?

### ISSUE THREAD

**Issue by nyanpasu64** [minrk/appnope#16]
I'm getting a deprecation warning in (Windows) CI in a program depending on (macOS-based) appnope:

```
..\..\Users\appveyor\AppData\Local\pypoetry\Cache\virtualenvs\corrscope-2f2v7ZI7-py3.8\lib\site-packages\appnope\__init__.py:8
  C:\Users\appveyor\AppData\Local\pypoetry\Cache\virtualenvs\corrscope-2f2v7ZI7-py3.8\lib\site-packages\appnope\__init__.py:8: DeprecationWarning: invalid escape sequence \d
    return tuple(int(s) for s in re.findall("\d+", version_s))
```

In https://github.com/minrk/appnope/blob/main/appnope/__init__.py, did you mean to write `r"\d+"` rather than `"\d+"`?

**Comment by minrk** [comment]
yup, that should be escaped. WiIl release 0.1.4 shortly

Can you tell what dependency is pulling in appnope? It's a bit odd to see appnope in a Windows environment.

**Comment by nyanpasu64** [comment]
https://github.com/corrscope/corrscope/ unconditionally depends on appnope and its decorator, and as I understand it's a no-op outside of macOS. Should I use a different approach for this dependency?

Also is it possible to allow `nope()` to take a custom string argument? (Or does it not matter since it's not actually human-visible?)

**Comment by minrk** [comment]
Not a big deal. appnope should be a safe noop.

The standard way would be to use [environment markers](https://peps.python.org/pep-0496/), [like this](https://github.com/ipython/ipykernel/blob/e8dd96143695967cdfe084bc49349eb667b91a76/pyproject.toml#L34):

```
appnope; platform_system=="Darwin"
```

to only depend on appnope on mac. And if you need a context manager in your code for consistent behavior, use [nullcontext](https://docs.python.org/3/library/contextlib.html#contextlib.nullcontext) from the standard library on non-mac platforms.

> Also is it possible to allow nope() to take a custom string argument?

What would a string argument do? appnope doesn't have any configurable behavior.
